contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
languageCode: "en-us"
title: "Juan Soto"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
relativeURLs: true

author:
  name: "Juan Soto"
